project_id = "qygthejhzgbjaawqhuny"

[functions.validate]
verify_jwt = false

[functions.create-reseller]
verify_jwt = false

[functions.create-manager]
verify_jwt = false

[functions.reset-hwid]
verify_jwt = false

[functions.heartbeat]
verify_jwt = false

[functions.delete-manager]
verify_jwt = false

[functions.check-license]
verify_jwt = false

[functions.check-plan-limits]
verify_jwt = false

[functions.get-download]
verify_jwt = false

[functions.create-nowpayments-checkout]
verify_jwt = false

[functions.nowpayments-webhook]
verify_jwt = false

[functions.sync-litecoin-payments]
verify_jwt = false
